import Link from "next/link";
import { ArrowRight, BriefcaseBusiness, GraduationCap, SearchCheck, ServerCog, Users } from "lucide-react";
import { SiteFooter, SiteHeader } from "./site-shell";
const services=[{icon:Users,title:"Human Capacity Development",text:"Structured programmes that strengthen people, teams and leadership performance."},{icon:GraduationCap,title:"Professional Training",text:"Practical, industry-relevant learning designed around measurable workplace outcomes."},{icon:SearchCheck,title:"Hiring & Recruitment",text:"Thoughtful talent sourcing, assessment and placement for organisations that value fit."},{icon:BriefcaseBusiness,title:"Business Consultancy",text:"Clear, context-aware guidance that helps organisations solve problems and grow well."},{icon:ServerCog,title:"Static Website Transfer",text:"Expert transfer of complete static websites from one hosting company to another, with every detail preserved."}];
export default function Home(){return <><SiteHeader active="home"/><main>
<section className="hero"><div className="heroImg"/><div className="shade"/><div className="container heroContent"><p className="eyebrow light">People. Performance. Possibility.</p><h1>Building the people<br/>who build organisations.</h1><p>Farbid International develops talent, equips professionals and helps organisations hire and perform with confidence.</p><div className="actions"><Link className="button coral" href="/services">Explore our services <ArrowRight size={18}/></Link><Link className="textLink lightLink" href="/about">Discover Farbid <ArrowRight size={17}/></Link></div></div></section>
<section className="section"><div className="container twoCol"><div><p className="eyebrow">Who we are</p><h2>Capability that creates lasting value.</h2></div><div><p className="lead">We are a Nigerian professional-services company focused on the most important engine of every organisation: its people.</p><p>From D-Line, Port Harcourt, we partner with individuals and businesses to close skills gaps, identify great talent and turn strategic intent into practical results.</p><Link className="textLink" href="/about">More about us <ArrowRight size={17}/></Link></div></div></section>
<section className="section dark"><div className="container"><div className="sectionHead"><div><p className="eyebrow light">What we do</p><h2>Solutions built around your ambitions.</h2></div><Link className="textLink lightLink" href="/services">View all services <ArrowRight size={17}/></Link></div><div className="serviceGrid">{services.map(({icon:Icon,title,text},i)=><article key={title}><span>0{i+1}</span><Icon/><h3>{title}</h3><p>{text}</p><Link href="/services"><ArrowRight/></Link></article>)}</div></div></section>
<section className="section"><div className="container proof"><div className="image"><img src="/images/training.jpg" alt="Professionals at a corporate training workshop"/></div><div><p className="eyebrow">Why Farbid</p><h2>Practical expertise. Human-centred delivery.</h2><p className="lead">We listen first, design deliberately and deliver with outcomes in mind.</p><ul><li><b>Context-aware</b><span>Solutions shaped for Nigerian organisations and global standards.</span></li><li><b>Outcome-led</b><span>Clear goals, practical learning and visible improvement.</span></li><li><b>Partnership-driven</b><span>Responsive support from first conversation to final result.</span></li></ul></div></div></section>
<section className="cta"><div className="container ctaInner"><div><p className="eyebrow">Let’s move forward</p><h2>Ready to strengthen your people or organisation?</h2></div><Link className="button gold" href="/contact">Start a conversation <ArrowRight size={18}/></Link></div></section>
</main><SiteFooter/></>}
